var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');
var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');
var districtreg = require('./routes/districtreg');
var districtview = require('./routes/districtview');
var locationview = require('./routes/locationview');
var categoryview = require('./routes/categoryview');
var login=require('./routes/login');
var locationreg=require('./routes/locationreg');
var stockreg=require('./routes/stockreg');
var locationdelete=require('./routes/locationdelete');
var locationedit=require('./routes/locationedit');
var categoryreg=require('./routes/categoryreg');
var categorydelete=require('./routes/categorydelete');
var getdistrictbyid=require('./routes/getdistrictbyid');
var getfurniturebyid=require('./routes/getfurniturebyid');
var getcategorydetails=require('./routes/getcategorydetails');
var updatecategory=require('./routes/updatecategory');
var furniturereg=require('./routes/furniturereg');
var getlocationdetails=require('./routes/getlocationdetails');
var Deletefurnituredata=require('./routes/Deletefurnituredata');
var updatefurniture=require('./routes/updatefurniture');
var furnitureview=require('./routes/furnitureview');
var furnituredetails=require('./routes/furnituredetails');
var customerreg=require('./routes/customerreg');
var furnitureexcel=require('./routes/furnitureexcel');
var addtocart=require('./routes/addtocart');
var cartview=require('./routes/cartview');
var Deletecartitem=require('./routes/Deletecartitem');
var carttotal=require('./routes/carttotal');
var booking=require('./routes/booking');
var getcustomer=require('./routes/getcustomer');
var delivery=require('./routes/delivery');
var categoryviewpie=require('./routes/categoryviewpie');
var viewcartdetails=require('./routes/viewcartdetails');
var viewgrandtotal=require('./routes/viewgrandtotal');
var report=require('./routes/report');
var stockexcel=require('./routes/stockexcel');
var payment=require('./routes/payment');
var reportpayment=require('./routes/reportpayment');
var forgotpassword=require('./routes/forgotpassword');
var changepassword=require('./routes/changepassword');
var updatecustomer=require('./routes/updatecustomer');
var paymentconfirm=require('./routes/paymentconfirm');
var logout=require('./routes/logout');
var upload=require('./routes/upload');
var app = express();
var cors =require("cors");
global.__basedir = path.resolve(path.dirname(''));
app.use(cors())
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));
app.use('/', indexRouter);
app.use('/users', usersRouter);
app.use('/districtreg', districtreg);
app.use('/locationreg', locationreg);
app.use('/districtview', districtview);
app.use('/locationview', locationview);
app.use('/categoryview', categoryview);
app.use('/categoryreg', categoryreg);
app.use('/getdistrictbyid', getdistrictbyid);
app.use('/locationdelete', locationdelete);
app.use('/categorydelete', categorydelete);
app.use('/getcategorydetails', getcategorydetails);
app.use('/locationedit', locationedit);
app.use('/getlocationdetails', getlocationdetails);
app.use('/updatecategory', updatecategory);
app.use('/furniturereg', furniturereg);
app.use('/furnitureview', furnitureview);
app.use('/getfurniturebyid', getfurniturebyid);
app.use('/Deletefurnituredata', Deletefurnituredata);
app.use('/updatefurniture', updatefurniture);
app.use('/furnituredetails', furnituredetails);
app.use('/customerreg', customerreg);
app.use('/addtocart', addtocart);
app.use('/cartview', cartview);
app.use('/stockreg', stockreg);
app.use('/Deletecartitem', Deletecartitem);
app.use('/carttotal', carttotal);
app.use('/booking', booking);
app.use('/getcustomer', getcustomer);
app.use('/categoryviewpie', categoryviewpie);
app.use('/furnitureexcel', furnitureexcel);
app.use('/reportpayment', reportpayment);
app.use('/stockexcel', stockexcel);
app.use('/delivery', delivery);
app.use('/forgotpassword', forgotpassword);
app.use('/upload', upload);
app.use('/login',login);
app.use('/viewcartdetails',viewcartdetails);
app.use('/viewgrandtotal',viewgrandtotal);
app.use('/changepassword',changepassword);
app.use('/updatecustomer',updatecustomer);
app.use('/paymentconfirm',paymentconfirm);
app.use('/report',report);
app.use('/logout',logout);
app.use('/payment',payment);
module.exports = app;
